### ISSUE TITLE
no mkimage.py file

### ISSUE THREAD

**Issue by InTheShadowCode** [RebornOS-Developers/lxqt-opi5-image#1]
Where is the mkimage.py file to create the image? Must i install from another package? Thanks!!

**Comment by Rippanda12** [comment]
I'm working on fixing it up since the code behind it is pretty garbage and will fail with custom configurations

**Comment by ricardomansano** [comment]
@InTheShadowCode , download from here
https://github.com/RebornOS-Developers/lxqt-opi5-image/releases

**Comment by Rippanda12** [comment]
@InTheShadowCode the code is now public [https://github.com/RebornOS-Developers/mkimage](https://github.com/RebornOS-Developers/mkimage)
